Set up jest-junit test reporting

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,3 +27,17 @@ jobs:
       run: cd frontend && npx tsc && cd ../backend && npx tsc
     - name: Test
       run: npm run test
+    - name: Frontend Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: Frontend Tests          # Name of the check run which will be created
+        path: frontend/reports/*.xml  # Path to test results
+        reporter: jest-junit          # Format of test results
+    - name: Backend Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: Backend Tests         # Name of the check run which will be created
+        path: backend/reports/*.xml    # Path to test results
+        reporter: jest-junit        # Format of test results
